added sandbox key to toggle dev/prod envs
beamkenya/ex_pesa pull request #19
Opened 2020-09-26 11:57 UTC by manuelgeek

Solution
Removed the `force-liveurl` key and added `sandbox` key to the `ex_pesa` configs. The key is a boolean to determine whether the keys added are for sandbox or live.

Re read on the README configs to understand better

2020-09-26 16:55 UTC, lenileiro approved these changes
LSTM

2020-09-28 14:19 UTC, lenileiro requested changes

2020-09-28 14:19 UTC, lenileiro commented on lib/ex_pesa/util.ex
> +      Application.get_env(:at_ex, :sandbox) === false -> live_url
Change at_ex to ex_pesa

2020-09-28 18:03 UTC, manuelgeek commented on lib/ex_pesa/util.ex
> +      Application.get_env(:at_ex, :sandbox) === false -> live_url
done, nice catch

2020-09-28 18:56 UTC, lenileiro approved these changes
@manuelgeek nice work

2020-09-28 18:58 UTC, merged