Implements B2B functionality
beamkenya/ex_pesa pull request #20
Opened 2020-09-27 14:20 UTC by lenileiro

## What is the Purpose?

resolve #11 

## What was the approach?

Briefly describe the approach used to address the issue

## Are there any concerns to addressed further before or after merging this PR?

State some additional info if any. For instance running `mix deps.get` or setting some environment variable(s)

## Mentions?

Mention persons you'd like to review this PR

## Issue(s) affected?

List of issues addressed by this PR.

2020-09-27 14:54 UTC, manuelgeek requested changes
@lenileiro 
1. Kindly if you have to edit another module  say STK, do it on a different PR,
2. You have modified so many files not related to the PR
3. Kindly squash all the commits into 1, too many commits, not easy to review

But generally any edits on c2b and stk modules and their config files is not going to be accepted in this PR, 

NICE JOB so far

2020-09-27 15:23 UTC, lenileiro commented
@manuelgeek I have removed all the key changes on the said files. I will follow up with another PR as advised.

2020-09-27 15:23 UTC, manuelgeek commented
@lenileiro  squash your commits into 1 13 commits are too much

2020-09-27 15:24 UTC, manuelgeek commented
I prefer you create a new PR< this PR has so many changes files

2020-09-27 17:02 UTC, manuelgeek commented on config/dev.sample.exs
> +    cert:
you can just put all `b2b` related keys within the `b2b` list you created

2020-09-27 18:27 UTC, manuelgeek commented on lib/ex_pesa/Mpesa/b2b.ex
you can add explanation that if you add the security credential, then it will be used instead of the password ans public key. Just for clarity

2020-09-27 18:28 UTC, manuelgeek commented
@lenileiro  I left a comment there, I will do the test, then revert, tomorrow .
Great stuff so far

2020-10-03 12:58 UTC, manuelgeek commented
@kamalogudah The test look OK, just fixed a little description'

2020-10-03 13:01 UTC, manuelgeek approved these changes

2020-10-03 13:15 UTC, lenileiro commented on lib/ex_pesa/Mpesa/b2b.ex
> +     "Required Parameter missing, 'CommandID','Amount','PartyB', 'Remarks','AccountReference'"}
PartyB to receiver_party
Change parameters to snake case

2020-10-03 13:15 UTC, lenileiro commented on test/ex_pesa/Mpesa/b2b_test.exs
> +      "Required Parameter missing, 'CommandID','Amount','PartyB', 'Remarks','AccountReference'" =
Change to snake case

2020-10-03 13:16 UTC, lenileiro commented
Nice work @kamalogudah and @manuelgeek

2020-10-03 13:32 UTC, manuelgeek commented
@lenileiro you can do the cleaup in utils.ex then i can merge it now

2020-10-03 14:04 UTC, manuelgeek approved these changes
all good to go now. merging this now @lenileiro @kamalogudah

2020-10-03 14:05 UTC, merged